export const ActionTypes = {
	SET_PRODUCTS: "SET_PRODUCTS",
	SELECTED_PRODUCT: "SELECTED_PRODUCT",
	REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

	SET_USER_AUTH: "SET_USER_AUTH",
	REMOVE_USER_AUTH: "REMOVE_USER_AUTH",
};
