export const ActionTypes = {
	SET_PRODUCTS: "SET_PRODUCTS",
	SELECTED_PRODUCT: "SELECTED_PRODUCT",
	REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

	SET_TOKEN: "SET_TOKEN",
	SET_USER_TYPE: "SET_USER_TYPE",
	SET_USER_AUTH: "SET_USER_AUTH",
	REMOVE_USER_AUTH: "REMOVE_USER_AUTH",

	SET_MENU: "SET_MENU",
	ADD_PRODUCT: "ADD_PRODUCT",
	SET_DASHBOARD: "SET_DASHBOARD",
	SET_ORDER_FILTER: "SET_ORDER_FILTER",
	SET_ORDER_DETAILS: "SET_ORDER_DETAILS",
	SET_PRODUCT_LINE: "SET_PRODUCT_LINE",
	SET_FLAVOUR: "SET_FLAVOUR",
	ADD_TO_CART: "ADD_TO_CART",
};
